USE store_rating_db;

-- Update Users Table
ALTER TABLE users 
ADD COLUMN status ENUM('Active', 'Inactive') DEFAULT 'Active',
ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Update Stores Table
ALTER TABLE stores
ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Update Ratings Table
ALTER TABLE ratings
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
